package me.thecuddlybear.Bot.extensions.models

import kotlinx.serialization.Serializable

/**
 * Represents a response generated by the HordeText model.
 *
 * @property text The generated text.
 * @property seed The seed used for text generation.
 * @property gen_metadata Additional metadata related to text generation.
 * @property worker_id The ID of the worker who generated the text.
 * @property worker_name The name of the worker who generated the text.
 * @property model The name of the model used for text generation.
 * @property state The state of the model at the time of text generation.
 */
@Serializable
data class HordeTextResponseGeneration(
    val text: String,
    val seed: Int,
    val gen_metadata: Array<String>,
    val worker_id: String,
    val worker_name: String,
    val model: String,
    val state: String
)